//punto 1(asignado a luz)
var nombre = "Ares";
var apellido = "Ferrari";
var edad = 22;
var ciudadNatal = "Argentina";

console.log("Nombre: " + nombre);
console.log("Apellido: " + apellido);
console.log("Edad: " + edad);
console.log("Ciudad Natal: " + ciudadNatal)
//punto 2(asignado a ramiro)

let nume1 = 10;
let numb2 = 5;

let sume = nume1 + numb2;
console.log("Suma:", sume);

let rest = nume1 - numb2;
console.log("Resta:", rest);

let force = nume1 * numb2;
console.log("Multiplicación:", force);

if (numb2 !== 0) {
    let divisione = nume1 / numb2;
    console.log("División:", divisione);
} else {
    console.log("Error: División por cero");
}

//punto 3(asignado a ivan)
let numero= 55555;
let cadena =numero.toString ();
console.log ("numero",cadena);
let cadena2 = "6666";
let numero2 = parseInt(cadena2);
console.log("cadena2",numero2);

//punto 4(asignado a franco "yeah, viva yo" NO)
let nombreB = prompt("ingresa tu nombre"); 
let edadB  = prompt("ingresa tu edad") ;
console.log ("nombre:"+nombreB + " edad:"+edadB );